#!/usr/bin/env python3

import datetime
import enum
import io
import os
import re
import shutil
import subprocess
from contextlib import redirect_stdout
from dataclasses import dataclass
from functools import reduce
from pathlib import Path
from typing import Dict, List, Optional

import click

SCRIPT_DIR = Path(__file__).resolve().parent

# --- Default configuration ---
DEFAULT_OFFLOAD_ROOT = os.path.expanduser("~/googledrive/development/KB-private-offloaded")
PATH_PREFIX_TO_STRIP = "cloudera/tasks/cde/"
KB_PRIVATE_ROOT = os.path.expanduser("~/development/my-repos/knowledge-base-private")
ALLOWED_EXTENSIONS = [".tar.gz", ".gz", ".zip", ".gzip"]
ANALYZER_DEFAULT_TOP_N = 200
# -----------------------------


def convert_bytes_to_human_readable(bytes: int) -> str:
    return f"{bytes / 1024 ** 3:.2f} GB" if bytes > 1024**3 else f"{bytes / 1024 ** 2:.2f} MB"


def sum_bytes_of_items(items: List[Dict]) -> int:
    if not items:
        return 0
    return reduce(lambda x, y: x + y, map(lambda x: x["size_bytes"], items))


def parse_human_size(size_str: str) -> Optional[int]:
    """
    Converts a human-readable size string (e.g., '1.7G', '5.1K', '128B') to bytes.
    It expects IEC units (B, K, M, G, T, P) as generated by numfmt --to=iec.
    """
    size_str = size_str.strip().upper()
    if not size_str:
        return None

    # Regex to capture the number and the unit (B, K, M, G, T, P)
    # The 'B' suffix is often optional in numfmt IEC output but we'll allow it.
    match = re.match(r"(\d+(\.\d+)?)\s*([KMGTPE])?B?", size_str)
    if not match:
        # Handle cases where the size is just a raw number of bytes
        if size_str.isdigit():
            return int(size_str)
        return None

    value = float(match.group(1))
    unit = match.group(3)

    units_map = {
        None: 1,  # Bytes
        "K": 1024,  # Kibibytes
        "M": 1024**2,  # Mebibytes
        "G": 1024**3,  # Gibibytes
        "T": 1024**4,  # Tebibytes
        "P": 1024**5,  # Pebibytes
    }

    multiplier = units_map.get(unit, 1)

    return int(value * multiplier)


def format_size_for_details_output(size_bytes: int) -> str:
    """Format bytes like git-commit-size-detailed.sh (numfmt --to=iec, single token)."""
    if size_bytes >= 1024**4:
        return f"{size_bytes / 1024 ** 4:.1f}T"
    if size_bytes >= 1024**3:
        return f"{size_bytes / 1024 ** 3:.1f}G"
    if size_bytes >= 1024**2:
        return f"{size_bytes / 1024 ** 2:.1f}M"
    if size_bytes >= 1024:
        return f"{size_bytes / 1024:.1f}K"
    return f"{size_bytes}B"


class GitCommitSizeAnalyzer:
    @staticmethod
    def build_chunk_sizes(top_n: int) -> List[int]:
        chunk_size = 20
        chunks = [2, 4, 6, 8, 10] + [i * chunk_size for i in range(int(top_n / chunk_size))] + [top_n]
        if 0 in chunks:
            chunks.remove(0)
        return chunks

    @staticmethod
    def analyze_sizes(data: str) -> List[Dict]:
        """
        Processes the raw file size data, sorts it, and returns the top N largest files.

        Args:
            data: A string containing lines of size and filename, separated by whitespace.

        Returns:
            A sorted list of file dictionaries.
        """
        results = []
        lines = data.strip().split("\n")

        for line in lines:
            try:
                # Split the line by whitespace
                parts = line.strip().split(maxsplit=1)
                if len(parts) != 2:
                    # Skip lines that don't have exactly two parts (size and filename)
                    continue

                human_size, filename = parts
                size_in_bytes = parse_human_size(human_size)

                if size_in_bytes is not None:
                    results.append(
                        {
                            "human_size": human_size.strip(),
                            "size_bytes": size_in_bytes,
                            "filename": filename.strip(),
                        }
                    )

            except Exception as e:
                # Print any parsing errors but continue processing the rest of the data
                print(f"Error parsing line '{line.strip()}': {e}")
                continue

        # Sort the results by 'size_bytes' in descending order
        results.sort(key=lambda x: x["size_bytes"], reverse=True)

        return results

    @staticmethod
    def write_sorted_file(results: List[Dict], output_path: Path) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with output_path.open("w") as temp_file:
            if results:
                max_size_len = max(len(r["human_size"]) for r in results)
                for i, item in enumerate(results):
                    # Print rank, human-readable size (left-padded for alignment), and filename
                    size_padded = item["human_size"].rjust(max_size_len)
                    temp_file.write(f"#{i+1}: {size_padded} -> {item['filename']}\n")

    @staticmethod
    def analyze_and_write(input_path: Path, all_sorted_out: Path, top_n: int = ANALYZER_DEFAULT_TOP_N) -> None:
        """Sort commit size data, print summary to stdout, write full sorted list to disk."""
        chunks = GitCommitSizeAnalyzer.build_chunk_sizes(top_n)
        raw_data = input_path.read_text()

        print(f"--- Analyzing Size Data from '{input_path}' (Top {top_n}) ---")

        # Analyze and get results
        results = GitCommitSizeAnalyzer.analyze_sizes(raw_data)
        GitCommitSizeAnalyzer.write_sorted_file(results, all_sorted_out)

        top_results = results[:top_n]

        if top_results:
            # Determine the maximum width for the size column for clean alignment
            max_size_len = max(len(r["human_size"]) for r in top_results)

            # Output the results
            for i, item in enumerate(top_results):
                # Print rank, human-readable size (left-padded for alignment), and filename
                size_padded = item["human_size"].rjust(max_size_len)
                print(f"#{i+1}: {size_padded} -> {item['filename']}")
        else:
            print("No valid file size data found to process.")

        print("-" * 50)
        print(f"Temporary file with all results ordered created at: {all_sorted_out}")

        # Print sums
        sum_bytes = sum_bytes_of_items(results)
        print(f"Sum size of all files: {convert_bytes_to_human_readable(sum_bytes)}")

        sum_chunks = []
        for c in chunks:
            sum_chunks.append(sum_bytes_of_items(results[:c]))

        for idx, sc in enumerate(sum_chunks):
            print(f"Sum of first {chunks[idx]} items: {convert_bytes_to_human_readable(sc)}")
        print(f"Sum of the rest of items: {convert_bytes_to_human_readable(sum_bytes_of_items(results[top_n:]))}")


class FileStats:
    def __init__(self):
        self.files_moved = 0
        self.files_skipped_by_extension = 0
        self.total_space_saved_bytes = 0
        self.total_space_reclaimed_non_matching_extension = 0

    def skip_file(self, file_path, size_in_bytes):
        self.files_skipped_by_extension += 1
        self.total_space_reclaimed_non_matching_extension += size_in_bytes

    def add_saved_space(self, size_in_bytes):
        self.total_space_saved_bytes += size_in_bytes

    def record_file_moved(self, file_path):
        self.files_moved += 1

    def print(self, dry_run: bool):
        print("-" * 60)
        print("Summary:")
        print(f"Files meeting size and extension criteria: {self.files_moved}")
        if self.files_skipped_by_extension > 0:
            print(f"Files skipped due to extension filter: {self.files_skipped_by_extension}")

        total_space_saved_human = convert_bytes_to_human_readable(self.total_space_saved_bytes)
        non_matching_human = convert_bytes_to_human_readable(self.total_space_reclaimed_non_matching_extension)
        if dry_run:
            print(f"Would save estimated space: {total_space_saved_human}")
            print(f"Would save estimated space for non-matching extensions: {non_matching_human}")
            print("\nNote: Re-run with --execute to perform the actual move.")
        else:
            print(f"Estimated Space Saved: {total_space_saved_human}")
            print(f"Space for non-matching extensions (not moved): {non_matching_human}")


class CandidateValidationCode(enum.Enum):
    FILE_PATTERN_DOES_NOT_MATCH = 0
    FILE_SIZE_BELOW_THRESHOLD = 1
    FILE_EXTENSION_NOT_ALLOWED = 2
    FILE_DOES_NOT_EXIST = 3
    VALID = 4


class FileMoveCandidate:
    def __init__(self, file_path: str):
        self.file_path = file_path
        self.size_in_bytes = -1
        self.human_size = -1
        self.paths = FileMoveCandidatePaths()


class FileMoveCandidatePaths:
    def __init__(self):
        self.source_path_abs: str = None
        self.repository_relative_filepath: str = None
        self.new_relative_path: str = None
        self.target_path_abs: str = None
        self.target_dir_abs: str = None
        self.placeholder_path: str = None


@dataclass
class FilePathValidationResult:
    code: CandidateValidationCode
    candidate: FileMoveCandidate


class FilePathValidator:
    def __init__(self, repo_root: str, allowed_extensions: List[str], threshold_bytes: int):
        self.repo_root = repo_root
        self.allowed_extensions = allowed_extensions
        self.threshold_bytes = threshold_bytes

    def is_ext_allowed(self, candidate, stats):
        is_allowed = False
        for ext in self.allowed_extensions:
            if candidate.paths.repository_relative_filepath.lower().endswith(ext):
                is_allowed = True
                break

        if not is_allowed:
            stats.skip_file(candidate.paths.repository_relative_filepath, candidate.size_in_bytes)
            return False
        return True

    def validate_candidate(self, file_path: str, stats: FileStats) -> FilePathValidationResult:
        # Use regex to robustly extract SIZE and FILENAME
        # Example format: #1: 1013MB -> cloudera/tasks/...
        c = FileMoveCandidate(file_path)
        match = re.search(r":\s*(\d+(\.\d+)?\s*[KMGTPE]?B?)\s*->\s*(.*)", c.file_path)

        if not match:
            return FilePathValidationResult(CandidateValidationCode.FILE_PATTERN_DOES_NOT_MATCH, c)

        # Set human size, repository_relative_filepath and size_in_bytes as early as possible
        c.human_size = match.group(1).strip()
        c.paths.repository_relative_filepath = match.group(3).strip()
        c.size_in_bytes = parse_human_size(c.human_size)

        if c.size_in_bytes is None or c.size_in_bytes < self.threshold_bytes:
            # Since the input is sorted, we can usually stop early, but checking all lines is safer.
            return FilePathValidationResult(CandidateValidationCode.FILE_SIZE_BELOW_THRESHOLD, c)

        if not self.is_ext_allowed(c, stats):
            return FilePathValidationResult(CandidateValidationCode.FILE_EXTENSION_NOT_ALLOWED, c)

        c.paths.source_path_abs = os.path.join(self.repo_root, c.paths.repository_relative_filepath)
        if not os.path.isfile(c.paths.source_path_abs):
            return FilePathValidationResult(CandidateValidationCode.FILE_DOES_NOT_EXIST, c)

        return FilePathValidationResult(CandidateValidationCode.VALID, c)


class GitLargeFileMover:
    def __init__(
        self,
        input_filepath: str,
        threshold_bytes: int,
        dry_run: bool = True,
        offload_root: str = DEFAULT_OFFLOAD_ROOT,
        path_prefix_to_strip: str = PATH_PREFIX_TO_STRIP,
        repo_root: str = KB_PRIVATE_ROOT,
        allowed_extensions: Optional[List[str]] = None,
    ):
        self.input_filepath = input_filepath
        self.threshold_bytes = threshold_bytes
        self.dry_run = dry_run
        self.offload_root = offload_root
        self.path_prefix_to_strip = path_prefix_to_strip
        self.repo_root = repo_root
        self.allowed_extensions = allowed_extensions

    def set_file_paths_for_candidate(self, c: FileMoveCandidate):
        rel_path = c.paths.repository_relative_filepath

        # Strip the configured prefix from the relative path
        if rel_path.startswith(self.path_prefix_to_strip):
            c.paths.new_relative_path = rel_path[len(self.path_prefix_to_strip) :]
        else:
            c.paths.new_relative_path = rel_path

        # Combine the clean relative path with the offload root
        c.paths.target_path_abs = os.path.join(self.offload_root, c.paths.new_relative_path)
        c.paths.target_dir_abs = os.path.dirname(c.paths.target_path_abs)
        c.paths.placeholder_path = c.paths.source_path_abs + ".MOVED.txt"

    def process_and_move(self) -> FileStats:  # noqa: C901
        """
        Reads the file list, identifies files larger than the threshold, and moves them
        to the offload root, preserving the relative path after stripping the prefix.
        It also creates a placeholder file in the original location upon a successful move.
        """
        if self.allowed_extensions is None:
            self.allowed_extensions = ALLOWED_EXTENSIONS

        if self.dry_run:
            print("!!! DRY RUN MODE ACTIVE !!!")
            print("No files will be moved. Commands are printed below.")
        else:
            print("!!! REAL MOVE MODE ACTIVE !!!")
            print(f"Files > {self.threshold_bytes // 1024 // 1024}MB will be MOVED to {self.offload_root}")

        print("-" * 60)
        print(f"NOTE: Stripping prefix '{self.path_prefix_to_strip}' from source paths.")
        print(f"NOTE: Only processing files with extensions: {', '.join(self.allowed_extensions)}")

        stats = FileStats()
        try:
            with open(self.input_filepath, "r") as f:
                raw_data = f.read()
        except Exception as e:
            print(f"Error reading input file: {e}")
            return stats

        lines = raw_data.strip().split("\n")
        validator = FilePathValidator(self.repo_root, self.allowed_extensions, self.threshold_bytes)

        current_candidate_no = 1
        for line in lines:
            # Skip header/footer lines and lines that don't look like file entries
            if not line.startswith("#"):
                continue

            # from now on, line is file_path
            file_path = line

            result = validator.validate_candidate(file_path, stats)
            if result.code in (
                CandidateValidationCode.FILE_SIZE_BELOW_THRESHOLD,
                CandidateValidationCode.FILE_PATTERN_DOES_NOT_MATCH,
                CandidateValidationCode.FILE_EXTENSION_NOT_ALLOWED,
                CandidateValidationCode.FILE_DOES_NOT_EXIST,
            ):
                if result.code == CandidateValidationCode.FILE_DOES_NOT_EXIST:
                    print(f"ERROR: File does not exist at source: {result.candidate.paths.source_path_abs}")
                continue

            c: FileMoveCandidate = result.candidate

            # Determine destination paths and print candidate
            self.set_file_paths_for_candidate(c)
            print(f"\n[MOVE Candidate #{current_candidate_no}: {c.human_size}]")
            print(f"  SOURCE: {c.paths.source_path_abs}")
            print(f"  TARGET: {c.paths.target_path_abs}")

            # Execute/Simulate directory creation
            if not self._make_dir_for_candidate(c):
                continue

            stats.add_saved_space(c.size_in_bytes)

            # Execute/Simulate file move
            self._perform_file_move(c, stats)
            current_candidate_no += 1
        stats.print(self.dry_run)
        return stats

    def _make_dir_for_candidate(self, c: FileMoveCandidate):
        if not self.dry_run:
            try:
                os.makedirs(c.paths.target_dir_abs, exist_ok=True)
                print(f"  Created directory: {c.paths.target_dir_abs}")
            except Exception as e:
                print(f"  ERROR creating directory: {e}")
                return False
            return True
        else:
            print(f"  Dry Run: mkdir -p {c.paths.target_dir_abs}")
            return True

    def _perform_file_move(self, c: FileMoveCandidate, stats: FileStats):
        if not self.dry_run:
            try:
                shutil.move(c.paths.source_path_abs, c.paths.target_path_abs)
                print("  SUCCESS: Moved file.")

                placeholder_content = (
                    "--- FILE MOVED ---\n"
                    f"Original file was moved by git_move_large_files.py on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.\n"
                    f"New location: {c.paths.target_path_abs}\n"
                    "--------------------\n"
                )

                with open(c.paths.placeholder_path, "w") as ph_file:
                    ph_file.write(placeholder_content)

                print(f"  SUCCESS: Created placeholder at {os.path.basename(c.paths.placeholder_path)}")
                stats.record_file_moved(c.file_path)
            except FileNotFoundError:
                print(f"  ERROR: Source file not found at {c.paths.source_path_abs}. Skipping.")
            except Exception as e:
                print(f"  ERROR moving file: {e}")
        else:
            print(f"  Dry Run: mv {c.paths.source_path_abs} {c.paths.target_path_abs}")
            print(f"  Dry Run: Creating placeholder file: {c.paths.placeholder_path}")
            stats.record_file_moved(c.file_path)


class GitLargeFileWorkflow:
    @staticmethod
    def verify_commit(repo: Path, commit: str) -> None:
        result = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--verify", f"{commit}^{{commit}}"],
            capture_output=True,
        )
        if result.returncode != 0:
            raise click.ClickException(f"commit '{commit}' not found in repository '{repo}'.")

    @staticmethod
    def run_commit_size_detailed(
        repo: Path,
        commit: str,
        output_path: Path,
        *,
        verbose: bool = False,
    ) -> None:
        script = SCRIPT_DIR / "git-commit-size-detailed.sh"
        cmd = [str(script), commit]
        if verbose:
            cmd.append("--verbose")
        with output_path.open("w") as out:
            subprocess.run(
                cmd,
                cwd=repo,
                stdout=out,
                check=True,
            )

    @staticmethod
    def run_working_tree_scan(repo: Path, output_path: Path, *, verbose: bool = False) -> None:
        tracked = subprocess.check_output(
            ["git", "ls-files", "-z"],
            cwd=repo,
        ).split(b"\0")

        paths = [raw.decode() for raw in tracked if raw]
        total = len(paths)
        if verbose:
            print(f"  Scanning {total} tracked path(s)...", flush=True)

        lines: List[str] = []
        for index, rel_path in enumerate(paths, start=1):
            abs_path = repo / rel_path
            if not abs_path.is_file():
                if verbose and (index == 1 or index % 500 == 0 or index == total):
                    print(f"  [{index}/{total}] skip (not a file): {rel_path}", flush=True)
                continue
            human_size = format_size_for_details_output(abs_path.stat().st_size)
            lines.append(f"{human_size} {rel_path}")
            if verbose and (index == 1 or index % 500 == 0 or index == total):
                print(f"  [{index}/{total}] {human_size}  {rel_path}", flush=True)

        output_path.write_text("\n".join(lines) + ("\n" if lines else ""))
        if verbose:
            print(f"  Sized {len(lines)} file(s) from working tree", flush=True)

    @staticmethod
    def run_analyzer(
        details_path: Path,
        analyzer_out: Path,
        all_sorted_out: Path,
        top_n: int = ANALYZER_DEFAULT_TOP_N,
    ) -> None:
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            GitCommitSizeAnalyzer.analyze_and_write(details_path, all_sorted_out, top_n=top_n)
        analyzer_out.write_text(buffer.getvalue())

    @staticmethod
    def run_mover(
        all_sorted_out: Path,
        mover_out: Path,
        *,
        threshold_mb: int,
        repo: Path,
        execute: bool,
        offload_root: Optional[str],
        path_prefix: Optional[str],
    ) -> FileStats:
        mover = GitLargeFileMover(
            str(all_sorted_out),
            threshold_mb * 1024 * 1024,
            dry_run=not execute,
            repo_root=str(repo),
            offload_root=os.path.expanduser(offload_root) if offload_root else DEFAULT_OFFLOAD_ROOT,
            path_prefix_to_strip=path_prefix if path_prefix else PATH_PREFIX_TO_STRIP,
        )
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            stats = mover.process_and_move()
        mover_out.write_text(buffer.getvalue())
        return stats

    @staticmethod
    def git_rm_deleted_files(repo: Path) -> None:
        deleted = subprocess.check_output(
            ["git", "ls-files", "--deleted"],
            cwd=repo,
            text=True,
        ).strip()
        if deleted:
            subprocess.run(
                ["git", "rm", *deleted.splitlines()],
                cwd=repo,
                check=True,
            )

    @staticmethod
    def git_add_moved_placeholders(repo: Path) -> None:
        for path in repo.rglob("*MOVED*"):
            if "REMOVED" in path.name:
                continue
            rel = path.relative_to(repo)
            subprocess.run(["git", "add", str(rel)], cwd=repo, check=True)

    @staticmethod
    def write_stage_summary(repo: Path, stage_summary_out: Path) -> None:
        status = subprocess.check_output(
            ["git", "status", "--short"],
            cwd=repo,
            text=True,
        )
        summary_lines = [line for line in status.splitlines() if re.search(r"deleted|^\?\?|^A ", line)]
        stage_summary_out.write_text("\n".join(summary_lines) + ("\n" if summary_lines else ""))

    @staticmethod
    def write_moved_contents(repo: Path, moved_contents_out: Path) -> None:
        cached = subprocess.check_output(
            ["git", "diff", "--name-only", "--cached"],
            cwd=repo,
            text=True,
        ).splitlines()
        moved_names = [name for name in cached if "MOVED" in name]

        parts: List[str] = []
        for filename in moved_names:
            parts.append(f"Processing file: {filename}")
            parts.append((repo / filename).read_text())
            parts.append("")
        moved_contents_out.write_text("\n".join(parts))

    @staticmethod
    def stage_changes(repo: Path, stage_summary_out: Path, moved_contents_out: Path) -> None:
        GitLargeFileWorkflow.git_rm_deleted_files(repo)
        GitLargeFileWorkflow.git_add_moved_placeholders(repo)
        GitLargeFileWorkflow.write_stage_summary(repo, stage_summary_out)
        GitLargeFileWorkflow.write_moved_contents(repo, moved_contents_out)

    @staticmethod
    def print_run_header(config: "WorkflowConfig", paths: "WorkflowOutputPaths") -> None:
        print(f"Repository: {config.resolved_repo()}")
        if config.scan_working_tree:
            print("Source: working tree (tracked files on disk)")
        else:
            print(f"Commit: {config.commit}")
        print(f"Output directory: {paths.out_dir}")
        print(f"Threshold: {config.threshold_mb}MB")
        print(f"Mode: {'EXECUTE (files will be moved)' if config.execute else 'DRY RUN (preview only)'}")
        if config.verbose:
            print("Verbose: enabled")
        print("")

    @staticmethod
    def collect_file_sizes(config: "WorkflowConfig", repo: Path, details_out: Path) -> None:
        if config.scan_working_tree:
            print("Step 1/3: Collecting file sizes from working tree...", flush=True)
            GitLargeFileWorkflow.run_working_tree_scan(repo, details_out, verbose=config.verbose)
        else:
            print("Step 1/3: Collecting file sizes from commit...", flush=True)
            if config.verbose:
                print(f"  Commit: {config.commit}", flush=True)
                print("  Running git-commit-size-detailed.sh (progress on stderr)...", flush=True)
            GitLargeFileWorkflow.run_commit_size_detailed(
                repo,
                config.commit,
                details_out,
                verbose=config.verbose,
            )
        print(f"  Wrote {details_out}", flush=True)

    @staticmethod
    def analyze_and_sort(paths: "WorkflowOutputPaths") -> None:
        print("Step 2/3: Sorting files by size...")
        GitLargeFileWorkflow.run_analyzer(paths.details_out, paths.analyzer_out, paths.all_sorted_out)
        print(f"  Wrote {paths.analyzer_out}")
        print(f"  Wrote {paths.all_sorted_out}")

    @staticmethod
    def _move_large_files(config: "WorkflowConfig", repo: Path, paths: "WorkflowOutputPaths") -> None:
        print("Step 3/3: Processing large files...")
        GitLargeFileWorkflow.run_mover(
            paths.all_sorted_out,
            paths.mover_out,
            threshold_mb=config.threshold_mb,
            repo=repo,
            execute=config.execute,
            offload_root=config.offload_root,
            path_prefix=config.path_prefix,
        )
        print(f"  Wrote {paths.mover_out}")

    @staticmethod
    def _stage_repo_changes(repo: Path, paths: "WorkflowOutputPaths") -> None:
        print("")
        print("Staging git changes...")
        GitLargeFileWorkflow.stage_changes(repo, paths.stage_summary_out, paths.moved_contents_out)
        print(f"  Wrote {paths.stage_summary_out}")
        print(f"  Wrote {paths.moved_contents_out}")
        print("")
        print(f"Review staged changes in {repo}, then commit when ready:")
        print(f"  cd {repo} && git status")

    @staticmethod
    def print_completion(config: "WorkflowConfig", paths: "WorkflowOutputPaths") -> None:
        print("")
        if config.execute:
            print("Done. Files were moved.")
        else:
            print(f"Dry run complete. Review {paths.mover_out}, then re-run with --execute.")

    @staticmethod
    def run(config: "WorkflowConfig") -> None:
        config.validate()
        repo = config.resolved_repo()
        out_dir = config.resolved_out_dir()
        out_dir.mkdir(parents=True, exist_ok=True)
        paths = WorkflowOutputPaths.for_run(out_dir, config.scan_working_tree, config.commit)

        if not config.scan_working_tree:
            GitLargeFileWorkflow.verify_commit(repo, config.commit)

        GitLargeFileWorkflow.print_run_header(config, paths)
        GitLargeFileWorkflow.collect_file_sizes(config, repo, paths.details_out)
        GitLargeFileWorkflow.analyze_and_sort(paths)
        GitLargeFileWorkflow._move_large_files(config, repo, paths)

        if config.stage:
            GitLargeFileWorkflow._stage_repo_changes(repo, paths)

        GitLargeFileWorkflow.print_completion(config, paths)


@dataclass
class WorkflowConfig:
    commit: Optional[str]
    scan_working_tree: bool
    repo: Path
    out_dir: Optional[Path]
    threshold_mb: int
    execute: bool
    stage: bool
    offload_root: Optional[str]
    path_prefix: Optional[str]
    verbose: bool = False

    def validate(self) -> None:
        if self.scan_working_tree and self.commit:
            raise click.UsageError("Use either --commit or --scan-working-tree, not both.")
        if not self.scan_working_tree and not self.commit:
            raise click.UsageError("Provide --commit or --scan-working-tree.")
        if self.stage and not self.execute:
            raise click.UsageError("--stage requires --execute (nothing to stage after a dry run).")

    @property
    def run_label(self) -> str:
        return "working-tree" if self.scan_working_tree else self.commit

    def resolved_repo(self) -> Path:
        return self.repo.expanduser().resolve()

    def resolved_out_dir(self) -> Path:
        if self.out_dir:
            return self.out_dir.expanduser().resolve()
        return Path.home() / f"git-large-files-{self.run_label}"

    def resolved_offload_root(self) -> str:
        if self.offload_root:
            return os.path.expanduser(self.offload_root)
        return DEFAULT_OFFLOAD_ROOT

    def resolved_path_prefix(self) -> str:
        if self.path_prefix:
            return self.path_prefix
        return PATH_PREFIX_TO_STRIP


@dataclass
class WorkflowOutputPaths:
    out_dir: Path
    details_out: Path
    analyzer_out: Path
    all_sorted_out: Path
    mover_out: Path
    stage_summary_out: Path
    moved_contents_out: Path

    @classmethod
    def for_run(cls, out_dir: Path, scan_working_tree: bool, commit: Optional[str]) -> "WorkflowOutputPaths":
        if scan_working_tree:
            details_out = out_dir / "git-details-working-tree.txt"
            analyzer_out = out_dir / "git-commit-size-analyzer-out-working-tree.txt"
            mover_out = out_dir / "git-large-file-mover-out-working-tree.txt"
        else:
            details_out = out_dir / f"git-details-hash-{commit}.txt"
            analyzer_out = out_dir / f"git-commit-size-analyzer-out-{commit}.txt"
            mover_out = out_dir / f"git-large-file-mover-out-{commit}.txt"

        return cls(
            out_dir=out_dir,
            details_out=details_out,
            analyzer_out=analyzer_out,
            all_sorted_out=out_dir / "git-commit-analyzer-all-results-sorted.txt",
            mover_out=mover_out,
            stage_summary_out=out_dir / "git-stage-summary.txt",
            moved_contents_out=out_dir / "contents-MOVED-files.txt",
        )


class ExpandedDirectoryPath(click.Path):
    """click.Path that expands ~ before existence checks."""

    def convert(self, value, param, ctx):
        if isinstance(value, Path):
            value = str(value.expanduser())
        else:
            value = os.path.expanduser(value)
        return super().convert(value, param, ctx)


@click.command(
    context_settings={"help_option_names": ["-h", "--help"]},
)
@click.option("--commit", help="Commit hash to analyze (required unless --scan-working-tree)")
@click.option(
    "--scan-working-tree",
    is_flag=True,
    help="Scan tracked files on disk instead of analyzing a single commit",
)
@click.option(
    "--repo",
    required=True,
    type=ExpandedDirectoryPath(exists=True, file_okay=False, path_type=Path),
    help="Local git repository root",
)
@click.option(
    "--out-dir",
    type=ExpandedDirectoryPath(file_okay=False, path_type=Path),
    help="Directory for intermediate output files (default: ~/git-large-files-<label>)",
)
@click.option(
    "--threshold-mb",
    default=20,
    show_default=True,
    help="Minimum file size in MB to move",
)
@click.option(
    "--execute/--dry-run",
    "execute",
    default=False,
    show_default=True,
    help="Actually move files to offloaded storage, or preview moves (default)",
)
@click.option(
    "--stage",
    is_flag=True,
    help="After moving, stage git rm/add for deleted files and MOVED placeholders",
)
@click.option("--offload-root", help=f"Offload destination root (default: {DEFAULT_OFFLOAD_ROOT})")
@click.option(
    "--path-prefix",
    help=f"Repository path prefix to strip before offload (default: {PATH_PREFIX_TO_STRIP})",
)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    help="Print progress while collecting file sizes (commit scan logs to stderr)",
)
def main(
    commit: Optional[str],
    scan_working_tree: bool,
    repo: Path,
    out_dir: Optional[Path],
    threshold_mb: int,
    execute: bool,
    stage: bool,
    offload_root: Optional[str],
    path_prefix: Optional[str],
    verbose: bool,
) -> None:
    """Analyze large files in a repo, optionally offload them, and optionally stage git changes."""
    GitLargeFileWorkflow.run(
        WorkflowConfig(
            commit=commit,
            scan_working_tree=scan_working_tree,
            repo=repo,
            out_dir=out_dir,
            threshold_mb=threshold_mb,
            execute=execute,
            stage=stage,
            offload_root=offload_root,
            path_prefix=path_prefix,
            verbose=verbose,
        )
    )


if __name__ == "__main__":
    main()
