import argparse
import os
import re
import sys
import tempfile
from functools import reduce
from typing import List, Dict, Optional


def convert_bytes_to_human_readable(bytes: int):
    return f"{bytes / 1024 ** 3:.2f} GB" if bytes > 1024**3 else f"{bytes / 1024 ** 2:.2f} MB"


def sum_bytes_of_items(items):
    if not items:
        return 0
    return reduce(lambda x, y: x + y, map(lambda x: x["size_bytes"], items))


def parse_human_size(size_str: str) -> Optional[int]:
    """
    Converts a human-readable size string (e.g., '1.7G', '5.1K', '128B') to bytes.
    It expects IEC units (B, K, M, G, T, P) as generated by numfmt --to=iec.
    """
    size_str = size_str.strip().upper()
    if not size_str:
        return None

    # Regex to capture the number and the unit (B, K, M, G, T, P)
    # The 'B' suffix is often optional in numfmt IEC output but we'll allow it.
    match = re.match(r"(\d+(\.\d+)?)\s*([KMGTPE])?B?", size_str)
    if not match:
        # Handle cases where the size is just a raw number of bytes
        if size_str.isdigit():
            return int(size_str)
        return None

    value = float(match.group(1))
    unit = match.group(3)

    units_map = {
        None: 1,  # Bytes
        "K": 1024,  # Kibibytes
        "M": 1024**2,  # Mebibytes
        "G": 1024**3,  # Gibibytes
        "T": 1024**4,  # Tebibytes
        "P": 1024**5,  # Pebibytes
    }

    multiplier = units_map.get(unit, 1)

    return int(value * multiplier)


def analyze_sizes(data: str) -> List[Dict]:
    """
    Processes the raw file size data, sorts it, and returns the top N largest files.

    Args:
        data: A string containing lines of size and filename, separated by whitespace.

    Returns:
        A sorted list of file dictionaries.
    """
    results = []
    lines = data.strip().split("\n")

    for line in lines:
        try:
            # Split the line by whitespace
            parts = line.strip().split(maxsplit=1)
            if len(parts) != 2:
                # Skip lines that don't have exactly two parts (size and filename)
                continue

            human_size, filename = parts
            size_in_bytes = parse_human_size(human_size)

            if size_in_bytes is not None:
                results.append(
                    {"human_size": human_size.strip(), "size_bytes": size_in_bytes, "filename": filename.strip()}
                )

        except Exception as e:
            # Print any parsing errors but continue processing the rest of the data
            print(f"Error parsing line '{line.strip()}': {e}")
            continue

    # Sort the results by 'size_bytes' in descending order
    results.sort(key=lambda x: x["size_bytes"], reverse=True)

    return results


def write_sorted_file(results: List[Dict], output_path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    with open(output_path, "w") as temp_file:
        if results:
            max_size_len = max(len(r["human_size"]) for r in results)
            for i, item in enumerate(results):
                size_padded = item["human_size"].rjust(max_size_len)
                temp_file.write(f"#{i+1}: {size_padded} -> {item['filename']}\n")

    return output_path


def write_to_temp_file(results: List[Dict]) -> str:
    with tempfile.NamedTemporaryFile(
        mode="w+t",
        delete=False,
        prefix="git-commit-analyzer-all-sorted-",
    ) as temp_file:
        temp_file_name = temp_file.name

    return write_sorted_file(results, temp_file_name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Sort commit file size data and show the largest files.",
    )
    parser.add_argument("input_filepath", help="Path to git-commit-size-detailed.sh output")
    parser.add_argument(
        "--all-sorted-out",
        help="Write the full sorted file list to this path (used by git_move_large_files.py)",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=200,
        help="Number of largest files to print to stdout (default: 200)",
    )
    args = parser.parse_args()

    top_n = args.top_n
    chunk_size = 20
    chunks = [2, 4, 6, 8, 10] + [i * chunk_size for i in range(int(top_n / chunk_size))] + [top_n]
    chunks.remove(0)

    input_filepath = args.input_filepath

    try:
        with open(input_filepath, "r") as f:
            raw_data = f.read()
    except FileNotFoundError:
        print(f"Error: The file '{input_filepath}' was not found.")
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred while reading the file: {e}")
        sys.exit(1)

    print(f"--- Analyzing Commit Size Data from '{input_filepath}' (Top {top_n}) ---")

    # 3. Analyze and get results
    results = analyze_sizes(raw_data)
    if args.all_sorted_out:
        all_sorted_path = write_sorted_file(results, os.path.expanduser(args.all_sorted_out))
    else:
        all_sorted_path = write_to_temp_file(results)

    top_results = results[:top_n]

    if top_results:
        # Determine the maximum width for the size column for clean alignment
        max_size_len = max(len(r["human_size"]) for r in top_results)

        # Output the results
        for i, item in enumerate(top_results):
            # Print rank, human-readable size (left-padded for alignment), and filename
            size_padded = item["human_size"].rjust(max_size_len)
            print(f"#{i+1}: {size_padded} -> {item['filename']}")
    else:
        print("No valid file size data found to process.")

    print("-" * 50)
    print(f"Temporary file with all results ordered created at: {all_sorted_path}")

    # Print sums
    sum_bytes = sum_bytes_of_items(results)
    print(f"Sum size of all files: {convert_bytes_to_human_readable(sum_bytes)}")

    sum_chunks = []
    for c in chunks:
        sum_chunks.append(sum_bytes_of_items(results[:c]))

    for idx, sc in enumerate(sum_chunks):
        print(f"Sum of first {chunks[idx]} items: {convert_bytes_to_human_readable(sc)}")
    print(f"Sum of the rest of items: {convert_bytes_to_human_readable(sum_bytes_of_items(results[top_n:]))}")
