alias start-google-chrome="google-chrome > /dev/null 2>&1"
#alias start-intellij="/usr/local/bin/idea > /dev/null 2>&1"
alias start-intellij="/usr/local/intellij-idea/bin/idea.sh"
alias start-squirrel="/usr/local/squirrel/squirrel-sql.sh > /dev/null 2>&1"
alias start-hipchat4="hipchat4 > /dev/null 2>&1"
